name: OpenStack Integration Dump Vars

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  dumpvars:
    runs-on: ubuntu-latest
    environment: openstack-integration

    steps:
      - uses: actions/checkout@v4

      - name: Dump environment values
        env:
          MY_REPO_VAR: ${{ vars.MY_REPO_VAR }}
          MY_REPO_SECRET: ${{ secrets.MY_REPO_SECRET }}
          MY_ENV_VAR: ${{ vars.MY_ENV_VAR }}
          MY_ENV_SECRET: ${{ secrets.MY_ENV_SECRET }}
        run: ./dumpvars.sh openstack-integration
