name: Test Workflow

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  check:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Run check
      env:
        MY_REPO_VAR: ${{ vars.MY_REPO_VAR }}
        MY_REPO_SECRET: ${{ secrets.MY_REPO_SECRET }}
        MY_ENV_VAR: ${{ vars.MY_ENV_VAR }}
        MY_ENV_SECRET: ${{ secrets.MY_ENV_SECRET }}
      run: ./dumpvars.sh check